import { BookOpen, Zap } from 'lucide-react';
import { TerminalCodeCell } from '../components/TerminalCodeCell';
import { CompleteLabButton } from '../components/CompleteLabButton';
import { useStore } from '../store/useStore';
import { createLLM } from '../utils/llmFactory';
import { celebrateCompletion } from '../utils/confetti';
import { t } from '../utils/translations';
import type { ExecutionResult } from '../types';

const TOTAL_LABS = 8;

export function Lab2() {
  const { apiKey, provider, selectedModel, markLabComplete, language } = useStore();

  const getLLMClass = () => {
    if (provider === 'browser') return 'WebLLM';
    return provider === 'groq' ? 'ChatGroq' : 'ChatCohere';
  };

  const getLLMImport = () => {
    if (provider === 'browser') {
      return `import * as webllm from '@mlc-ai/web-llm';`;
    }
    return provider === 'groq'
      ? `import { ChatGroq } from '@langchain/groq';`
      : `import { ChatCohere } from '@langchain/cohere';`;
  };

  const getLLMInit = () => {
    if (provider === 'browser') {
      return `// Browser LLM - runs locally, no API key needed!
const engine = await webllm.CreateMLCEngine('${selectedModel}');
const llm = {
  invoke: async (messages) => {
    const reply = await engine.chat.completions.create({ messages });
    return { content: reply.choices[0].message.content };
  }
}`;
    }
    return `const llm = new ${getLLMClass()}({
  apiKey: '${apiKey ? '***YOUR_API_KEY***' : 'your-api-key-here'}',
  model: '${selectedModel}',
})`;
  };

  const step1Code = `// Step 1: Import the ${provider === 'browser' ? 'WebLLM library' : `LangChain ${getLLMClass()} class`}
${getLLMImport()}

console.log('✓ ${provider === 'browser' ? 'WebLLM' : 'LangChain'} imported successfully!');`;

  const step2Code = `// Step 2: ${provider === 'browser' ? 'Create a Browser LLM instance (no API key needed!)' : 'Create an LLM instance with your API key'}
${getLLMInit()};

console.log('✓ LLM instance created with model: ${selectedModel}');`;

  const step3Code = `// Step 3: Define your prompt
const prompt = "What are the three main components of an AI agent?";

console.log('✓ Prompt ready:', prompt);`;

  const step4Code = `// Step 4: Get a response from the LLM
// This is where the MAGIC happens - we communicate with the AI!

${getLLMInit()};

// Your prompt (question/instruction for the AI)
// Clear, specific prompts lead to better responses
const prompt = "What are the three main components of an AI agent?";

// Call the LLM using invoke()
// - llm.invoke() sends your prompt to the AI model
// - The model processes the text and generates a response
// - 'await' waits for the response (this is an async operation)
// - Response comes back as an object with a 'content' property
const response = await llm.invoke(prompt);

// Display the AI's response
// response.content contains the actual text generated by the LLM
console.log('Response:', response.content);

// What just happened?
// 1. Your prompt was sent to the LLM API (Groq or Cohere)
// 2. The model processed billions of parameters to generate a response
// 3. The response traveled back over the internet to your browser
// 4. All in just a few seconds!`;

  const step5Code = `// Complete Example: Your First Working AI Agent!
// This is a REAL, FUNCTIONAL AI agent in just a few lines of code!

${getLLMImport()}

// Initialize the LLM
// This creates your connection to the AI model
${getLLMInit()};

// Send a prompt and get response
// Try changing this prompt to ask anything you want!
const prompt = "Explain what an AI agent is in one sentence.";

// The agent processes your request and generates a response
const response = await llm.invoke(prompt);

// Display the agent's response
console.log('Agent Response:', response.content);

// 🎉 Congratulations! You just built an AI agent!
// This simple agent already has:
// ✓ LLM (the brain - the AI model)
// ✓ Input (your prompt)
// ✓ Output (the response)

// What makes this an "agent"?
// - It receives input (your prompt)
// - It processes using intelligence (the LLM)
// - It produces output (the response)
// - All happening autonomously!

// Next level: Add system prompts to give your agent a personality!`;

  const executeStep1 = async (): Promise<ExecutionResult> => {
    try {
      return {
        output: '✓ LangChain imported successfully!',
        timestamp: Date.now(),
      };
    } catch (error) {
      return {
        output: '',
        error: error instanceof Error ? error.message : 'Unknown error',
        timestamp: Date.now(),
      };
    }
  };

  const executeStep2 = async (): Promise<ExecutionResult> => {
    try {
      if (!apiKey && provider !== 'browser') {
        throw new Error('Please configure your API key in Settings');
      }
      return {
        output: `✓ LLM instance created with model: ${selectedModel}`,
        timestamp: Date.now(),
      };
    } catch (error) {
      return {
        output: '',
        error: error instanceof Error ? error.message : 'Unknown error',
        timestamp: Date.now(),
      };
    }
  };

  const executeStep3 = async (): Promise<ExecutionResult> => {
    try {
      const prompt = "What are the three main components of an AI agent?";
      return {
        output: `✓ Prompt ready: ${prompt}`,
        timestamp: Date.now(),
      };
    } catch (error) {
      return {
        output: '',
        error: error instanceof Error ? error.message : 'Unknown error',
        timestamp: Date.now(),
      };
    }
  };

  const executeStep4 = async (): Promise<ExecutionResult> => {
    try {
      if (!apiKey && provider !== 'browser') {
        throw new Error('Please configure your API key in Settings');
      }

      const llm = createLLM(apiKey || 'browser-llm', provider, selectedModel);

      const prompt = "What are the three main components of an AI agent?";
      const response = await llm.invoke(prompt);

      return {
        output: `Response: ${response.content}`,
        timestamp: Date.now(),
      };
    } catch (error) {
      return {
        output: '',
        error: error instanceof Error ? error.message : 'Unknown error',
        timestamp: Date.now(),
      };
    }
  };

  const executeStep5 = async (): Promise<ExecutionResult> => {
    try {
      if (!apiKey && provider !== 'browser') {
        throw new Error('Please configure your API key in Settings');
      }

      const llm = createLLM(apiKey || 'browser-llm', provider, selectedModel);

      const prompt = "Explain what an AI agent is in one sentence.";
      const response = await llm.invoke(prompt);

      // Mark lab complete and show celebration
      markLabComplete(2);
      celebrateCompletion();

      return {
        output: `Agent Response: ${response.content}`,
        timestamp: Date.now(),
      };
    } catch (error) {
      return {
        output: '',
        error: error instanceof Error ? error.message : 'Unknown error',
        timestamp: Date.now(),
      };
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 sm:space-y-8 animate-fade-in w-full">
      <div className="hero-image-container mb-6 sm:mb-8 rounded-xl sm:rounded-2xl overflow-hidden border-2 border-cyan-500/30 shadow-2xl">
        <img
          src="/lab2-hero.jpg"
          alt="Lab 2: Simple Prompt/Response Agent"
          className="w-full h-auto object-cover"
        />
      </div>

      <div className="mb-6 sm:mb-8 rounded-xl sm:rounded-2xl overflow-hidden border-2 border-purple-500/30 shadow-2xl bg-black/40 backdrop-blur-sm">
        <img
          src="/lab2-diagram.png"
          alt="Prompt/Response Flow Diagram"
          className="w-full h-auto object-cover hover:scale-105 transition-transform duration-500"
        />
      </div>

      <div className="bg-gradient-to-br from-white to-slate-50 dark:from-slate-800 dark:to-slate-900 rounded-xl sm:rounded-2xl shadow-xl p-4 sm:p-6 md:p-8 border border-slate-200 dark:border-slate-700">
        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3 sm:gap-4 mb-4">
          <div className="p-2 sm:p-3 bg-gradient-to-br from-blue-500 to-cyan-600 rounded-lg sm:rounded-xl shadow-lg flex-shrink-0">
            <Zap className="w-6 h-6 sm:w-8 sm:h-8 text-white" />
          </div>
          <div>
            <h1 className="text-xl sm:text-2xl md:text-3xl font-bold text-slate-900 dark:text-slate-100">
              {t(language, 'lab2.title')}
            </h1>
            <p className="text-sm sm:text-base text-slate-600 dark:text-slate-400 mt-1">
              {t(language, 'lab2.subtitle')}
            </p>
          </div>
        </div>

        <div className="flex items-start gap-2 sm:gap-3 p-3 sm:p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg">
          <BookOpen className="w-4 h-4 sm:w-5 sm:h-5 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" />
          <div className="text-xs sm:text-sm text-blue-900 dark:text-blue-100">
            <p className="font-semibold mb-2">{t(language, 'lab2.whatYouLearn')}</p>
            <ul className="space-y-1 list-disc list-inside">
              <li>{t(language, 'lab2.learn1')}</li>
              <li>{t(language, 'lab2.learn2')}</li>
              <li>{t(language, 'lab2.learn3')}</li>
              <li>{t(language, 'lab2.learn4')}</li>
            </ul>
          </div>
        </div>
      </div>

      <div className="space-y-4 sm:space-y-6">
        <div className="flex items-center gap-2 sm:gap-3">
          <div className="flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 bg-gradient-to-br from-emerald-500 to-green-600 text-white rounded-full flex items-center justify-center font-bold text-sm sm:text-lg shadow-lg">
            1
          </div>
          <h2 className="text-lg sm:text-xl font-semibold text-slate-900 dark:text-slate-100">
            {t(language, 'lab2.step1Title')}
          </h2>
        </div>
        <TerminalCodeCell
          title="step-1-import"
          initialCode={step1Code}
          description={`${language === 'he' ? 'ראשית, אנו מייבאים את המחלקה' : 'First, we import the'} ${getLLMClass()} ${t(language, 'lab2.step1Desc')}`}
          onExecute={executeStep1}
        />
      </div>

      <div className="space-y-4 sm:space-y-6">
        <div className="flex items-center gap-2 sm:gap-3">
          <div className="flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 bg-gradient-to-br from-blue-500 to-cyan-600 text-white rounded-full flex items-center justify-center font-bold text-sm sm:text-lg shadow-lg">
            2
          </div>
          <h2 className="text-lg sm:text-xl font-semibold text-slate-900 dark:text-slate-100">
            {t(language, 'lab2.step2Title')}
          </h2>
        </div>
        <TerminalCodeCell
          title="step-2-create-llm"
          initialCode={step2Code}
          description={t(language, 'lab2.step2Desc')}
          onExecute={executeStep2}
        />
      </div>

      <div className="space-y-4 sm:space-y-6">
        <div className="flex items-center gap-2 sm:gap-3">
          <div className="flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 bg-gradient-to-br from-purple-500 to-pink-600 text-white rounded-full flex items-center justify-center font-bold text-sm sm:text-lg shadow-lg">
            3
          </div>
          <h2 className="text-lg sm:text-xl font-semibold text-slate-900 dark:text-slate-100">
            {t(language, 'lab2.step3Title')}
          </h2>
        </div>
        <TerminalCodeCell
          title="step-3-prompt"
          initialCode={step3Code}
          description={t(language, 'lab2.step3Desc')}
          onExecute={executeStep3}
        />
      </div>

      <div className="space-y-4 sm:space-y-6">
        <div className="flex items-center gap-2 sm:gap-3">
          <div className="flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 bg-gradient-to-br from-orange-500 to-red-600 text-white rounded-full flex items-center justify-center font-bold text-sm sm:text-lg shadow-lg">
            4
          </div>
          <h2 className="text-lg sm:text-xl font-semibold text-slate-900 dark:text-slate-100">
            {t(language, 'lab2.step4Title')}
          </h2>
        </div>
        <TerminalCodeCell
          title="step-4-response"
          initialCode={step4Code}
          description={t(language, 'lab2.step4Desc')}
          onExecute={executeStep4}
        />
      </div>

      <div className="space-y-4 sm:space-y-6">
        <div className="flex items-center gap-2 sm:gap-3">
          <div className="flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 bg-gradient-to-br from-indigo-500 to-purple-600 text-white rounded-full flex items-center justify-center font-bold text-sm sm:text-lg shadow-lg animate-pulse-glow">
            5
          </div>
          <h2 className="text-lg sm:text-xl font-semibold text-slate-900 dark:text-slate-100">
            {t(language, 'lab2.step5Title')}
          </h2>
        </div>
        <TerminalCodeCell
          title="complete-agent"
          initialCode={step5Code}
          description={t(language, 'lab2.step5Desc')}
          onExecute={executeStep5}
        />
      </div>

      <div className="bg-gradient-to-r from-green-50 to-emerald-50 dark:from-green-900/20 dark:to-emerald-900/20 rounded-lg sm:rounded-xl p-4 sm:p-6 border border-green-200 dark:border-green-800">
        <h3 className="font-semibold text-green-900 dark:text-green-100 mb-2 text-sm sm:text-base">
          🎉 {t(language, 'lab2.congratsTitle')}
        </h3>
        <p className="text-green-800 dark:text-green-200 text-xs sm:text-sm">
          {t(language, 'lab2.congratsText')}
        </p>
      </div>

      <CompleteLabButton labId={2} />
    </div>
  );
}
